apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV3TWpJdwpNalF4TURkYUZ3MDBNakV3TWpJd01qUXhNRGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEWkg3Lytibysxc3hjVGNrQjlZekNuNUsrV3lMUmVkSk9BaWtVcVF6Z0pkalJscU00MgozbnRiRE04N3pVWS9LR3I5TVlQOFo1aERvRWl2eWlPU3dSQVF4alRRUlRBdkt5OUFnOUt6c1luSm9wTEFrdS9MCnBBcytPRit6QklWeGNZdzhoRGIwYnJtRVFIdEFxc0doQlpGY1ZwWmMxbmhJQzhBSWFWK3ZPRWhqQ25neFB0UFgKYys5b0NEMXdRR294UkQzOUt3a2ZXNG1PSEpBZHVFZnlyeUsyTEFUeldjM2dQWEhCYTI4MmNhTERTWXJqZnpFRApaWjdFNmVQU0VEdnlCcW9RUExvcjlLUm5Wb1VoQlZNRmxMVlBkeHFQMnB1SEw4WmFtZjYwSjdqdnhTeGEwSnpECnhLN1Jnd1Q4K1M3QjNob3d4OUxWWndFVzRmWXMrUTNldDhJMUFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRTd3ZJQ0NCOUxvcGpkV3ZzZQo2Y1hRSWsxTWdUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFQZWdORzlWZTdxYVZVN1h2MjRwektVZXdIVEFRCjMxdTF3azFBYVdndlh1VndMbmhPbUdrUkVwQjJlK01TdFh5dmVhY1dJNXVmTERYRE40VlMzTEJmUTZpZ3E1UFcKb0h6ZmY0Ris4YWJsUHBzVFRPZDdPUlByWCt0NFZLL3NyWDd4ZHhOZUt3aVNTUkNxeTk0OTFJWXRudUlKa1d1dwpMMzlsS2ZSK0g3bnRLNDF4UUFpaS9LSXJZVXhOb2RjcTBSQnd2dlJxaHhjT2pKZjQycjF1bk4yUFJmNHc5TEFhCnBQNG5BREhTOWZvWWNNaC9VV2hJejRUSm1YdjNPQzlhaUFqNzJqdkFtWFhaS2ZSUW1uZmw0NFhkM0t6eGtlTG4KRFlvWnZaME1OUXhyRTk0UmN6dytKQS9HdkZSWW8rOXJMbXlONjg0cVZvSlA3OHpUN1U5eWNtcnpBdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6f4cced7-7a35-49ae-8937-d561fef70e8f.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_d785456d23c75acd8076e1e1416e1976cf8d96bc3133eb9931ae46be8e7e7fcb
